version: '3'

networks:
  back:

services:
  api:
    image: lucifer-api:latest
    build: ./
    networks:
      - back
    ports:
    - 8001:8000

  postgres:
    image: postgres:12-alpine
    networks:
      back:
        aliases:
          - postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
