# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build docker image

on:
  push:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Test & Build
        env:
          CI: true
        run: |
          yarn install --pure-lockfile
          yarn test
          yarn run build
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: lucifer-api
          path: build
      - name: Login to Github registry
        run: docker login docker.pkg.github.com -u jujulego -p ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        run: |
          export IMAGE_NAME=docker.pkg.github.com/jujulego/lucifer-api/lucifer-api
          export IMAGE_TAG=$(echo ${GITHUB_REF:10})

          docker build . --tag lucifer-api

          docker tag lucifer-api $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:$IMAGE_TAG
